kind: Service
apiVersion: v1
metadata:
  name: despliegue
spec:
  type: NodePort
  selector:
    app: despliegue
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-deploy
  labels:
    app: despliegue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despliegue
  template:
    metadata:
      labels:
        app: despliegue
    spec:
      containers:
      - name: despliegue
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
